# Generated by Django 5.2.6 on 2025-11-24 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('job_id', models.CharField(help_text='FastAPI 側で発行したジョブID等を保存しておくためのフィールド。', max_length=64, unique=True, verbose_name='ジョブID')),
                ('kind', models.CharField(choices=[('image', '画像チェック'), ('text', 'テキストチェック'), ('compat', '互換性チェック')], default='image', max_length=16, verbose_name='チェック種別')),
                ('status', models.CharField(choices=[('pending', 'キュー待ち'), ('running', '実行中'), ('done', '完了'), ('failed', '失敗')], default='done', max_length=16, verbose_name='ステータス')),
                ('input_filename', models.CharField(blank=True, help_text='アップロードされた元ファイル名（画像チェック時のみ）。', max_length=255, verbose_name='入力ファイル名')),
                ('input_mime', models.CharField(blank=True, max_length=100, verbose_name='MIMEタイプ')),
                ('input_prompt', models.TextField(blank=True, help_text='画像生成AIのプロンプトやテキストの補足説明など任意情報。', verbose_name='プロンプト / 補足説明')),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='クライアントIP')),
                ('user_agent', models.TextField(blank=True, verbose_name='ユーザーエージェント')),
                ('risk_score', models.FloatField(blank=True, help_text='0〜100 の著作権リスクスコア。', null=True, verbose_name='リスクスコア')),
                ('risk_level', models.CharField(blank=True, choices=[('低', '低'), ('中', '中'), ('高', '高')], help_text='低 / 中 / 高。', max_length=4, verbose_name='リスクレベル')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='FastAPI 側の /check/image /check/text から返された JSON 全体。', verbose_name='レスポンスペイロード')),
                ('user', models.ForeignKey(blank=True, help_text='チェックを実行したユーザー（匿名実行の場合は空）。', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'チェックジョブ',
                'verbose_name_plural': 'チェックジョブ一覧',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('username', models.CharField(blank=True, help_text='ログイン時点のユーザー名（後から変更されてもここには当時の値が残る）。', max_length=150, verbose_name='ユーザー名スナップショット')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='メールアドレススナップショット')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IPアドレス')),
                ('user_agent', models.TextField(blank=True, verbose_name='ユーザーエージェント')),
                ('is_admin_login', models.BooleanField(default=False, help_text='管理者専用ログイン画面からのログインであれば True。', verbose_name='管理者ログインか')),
                ('user', models.ForeignKey(blank=True, help_text='ログインしたユーザー（存在しない / 削除済みの場合は None）。', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ログイン履歴',
                'verbose_name_plural': 'ログイン履歴一覧',
                'ordering': ('-created_at',),
            },
        ),
    ]
